"""
create_pr.py — Scratch Research Co.

Creates a GitHub PR for the generated article so the human can review
before it publishes. Requires GH_TOKEN and GITHUB_REPOSITORY env vars
(automatically set in GitHub Actions).

Usage:
    python pipeline/create_pr.py

Reads: data/generation_manifest.json
Creates: a git branch, commits the article, opens a PR
"""

import os
import sys
import json
import subprocess
import urllib.request
import urllib.error
import datetime
from pathlib import Path

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data"

GH_TOKEN = os.environ.get("GH_TOKEN", "")
GITHUB_REPOSITORY = os.environ.get("GITHUB_REPOSITORY", "")  # owner/repo


def gh_api(path: str, method: str = "GET", body: dict = None) -> dict | None:
    """Call GitHub REST API."""
    url = f"https://api.github.com{path}"
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(url, data=data, method=method, headers={
        "Authorization": f"Bearer {GH_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
        "User-Agent": "ScratchResearchCo-Pipeline/1.0",
    })
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        body_text = e.read().decode()
        print(f"  [warn] GitHub API HTTP {e.code}: {body_text[:200]}")
        return None
    except Exception as e:
        print(f"  [warn] GitHub API error: {e}")
        return None


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run a shell command."""
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(ROOT))
    if check and result.returncode != 0:
        print(f"  [error] Command failed: {' '.join(cmd)}")
        print(f"  stdout: {result.stdout}")
        print(f"  stderr: {result.stderr}")
        sys.exit(1)
    return result


def main():
    print("\n=== Scratch Research Co. — Create Review PR ===\n")

    if not GH_TOKEN:
        print("ERROR: GH_TOKEN not set")
        sys.exit(1)
    if not GITHUB_REPOSITORY:
        print("ERROR: GITHUB_REPOSITORY not set")
        sys.exit(1)

    # Load manifest
    manifest_path = DATA_DIR / "generation_manifest.json"
    if not manifest_path.exists():
        print("ERROR: data/generation_manifest.json not found. Run generate_article.py first.")
        sys.exit(1)

    manifest = json.loads(manifest_path.read_text())
    article_path = manifest["article_path"]
    article_slug = manifest["article_slug"]
    tournament = manifest.get("tournament", "Golf Week")
    winner = manifest.get("winner", "")
    picks = manifest.get("picks", [])

    today = datetime.date.today().isoformat()
    branch_name = f"draft/article-{article_slug}"

    print(f"  Article: {article_path}")
    print(f"  Branch:  {branch_name}")

    # Git setup
    run(["git", "config", "user.email", "pipeline@scratch-research-co.com"])
    run(["git", "config", "user.name", "Scratch Research Co. Pipeline"])

    # Create branch from main
    run(["git", "checkout", "-b", branch_name])

    # Stage all new/changed files
    run(["git", "add", article_path])
    run(["git", "add", "picks/picks-history.json"], check=False)
    run(["git", "add", "data/"], check=False)

    # Commit
    commit_msg = f"draft: {tournament} — {today}"
    run(["git", "commit", "-m", commit_msg])

    # Push branch
    remote_url = f"https://x-access-token:{GH_TOKEN}@github.com/{GITHUB_REPOSITORY}.git"
    run(["git", "remote", "set-url", "origin", remote_url])
    run(["git", "push", "-u", "origin", branch_name])

    # Build PR body
    picks_md = ""
    if picks:
        picks_md = "\n\n**This Week's Picks:**\n" + "\n".join(f"- {p}" for p in picks)

    winner_line = f"\n**Winner:** {winner}" if winner else ""

    pr_body = f"""## {tournament} — {today}

Weekly article draft generated by the Scratch Research Co. pipeline.
Review the article, make any edits you'd like, then **merge this PR to publish**.{winner_line}{picks_md}

---

**To publish:** Merge this PR → GitHub Actions will build & deploy to GitHub Pages automatically.

**To edit:** Checkout the branch `{branch_name}`, make changes, push — the PR will update.

> _Generated by Scratch Research Co. Pipeline · {today}_
"""

    # Create PR
    print("\n  Creating GitHub PR...")
    pr = gh_api(
        f"/repos/{GITHUB_REPOSITORY}/pulls",
        method="POST",
        body={
            "title": f"[Draft] {tournament} — {today}",
            "body": pr_body,
            "head": branch_name,
            "base": "main",
            "draft": False,
        },
    )

    if pr:
        pr_url = pr.get("html_url", "")
        pr_number = pr.get("number", "?")
        print(f"\n✓ PR #{pr_number} created: {pr_url}")
        print("\nNext steps:")
        print("  1. Review the article at the PR link above")
        print("  2. Edit if needed")
        print("  3. Merge the PR → auto-publishes to GitHub Pages")

        # Write PR URL to manifest for any downstream steps
        manifest["pr_url"] = pr_url
        manifest["pr_number"] = pr_number
        manifest_path.write_text(json.dumps(manifest, indent=2))
    else:
        print("\n[warn] PR creation may have failed. Check GitHub manually.")
        sys.exit(1)


if __name__ == "__main__":
    main()
